### Hae kaikki blogit
GET http://localhost:3003/api/blogs

### Lisää uusi blogi
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Second Blog",
  "author": "Another Name",
  "url": "http://example2.com",
  "likes": 10
}
### Käyttäjän lisääminen
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Saukko",
  "name": "Anne Henriikka",
  "password": "salainen"
}
