### Hae kaikki blogit
GET http://localhost:3003/api/blogs

### Lisää uusi blogi
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Seconds Blogs",
  "author": "Anothers Names",
  "url": "http://example2.com",
  "likes": 13,
  "userId": "676f923ef034c33300079810"
}
### Käyttäjän lisääminen
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Saukko",
  "name": "Anne Henriikka",
  "password": "salainen"
}
